"""Winning projects from recent MLH hackathons, used to make realistic synthetic attendees (AR3).

Source: HackGT 12 (an MLH member event) Devpost gallery, winners only:
https://hackgt-12.devpost.com/project-gallery (collected 2026-09-26). Public project info only: name,
tagline, "Built with" list, prize. NO team member names or photos are stored or used: every synthetic
attendee gets a made-up name and an initials avatar (MASTER_SPEC AR3, privacy rules).

`topics` = what the project is about (hand-tagged from the tagline), `career` = roles its builders would
likely look for. Add more MLH events by appending rows with the same keys.
"""

EVENT = "HackGT 12"

WINNERS = [
    dict(name="Dose", tagline="IoT medication tracker + web dashboard", prize="Best Overall - 1st",
         tech=["esp32", "3d printing", "next.js", "react", "supabase", "embedded systems"],
         topics=["healthcare", "iot", "hardware"], career=["health tech", "hardware startups"]),
    dict(name="RefNet", tagline="Search, visualize, and analyze research papers", prize="Best Overall - 2nd",
         tech=["react", "d3.js", "flask", "python", "tailwind css"],
         topics=["data visualization", "knowledge graphs", "research tools"], career=["ai research", "data science"]),
    dict(name="vibesB2B", tagline="Vibe check the Zoom call", prize="Best Overall - 3rd",
         tech=["electron", "python", "opencv", "mediapipe", "tensorflow", "gemini", "typescript"],
         topics=["computer vision", "sales tech", "ai agents"], career=["startups", "ml engineering"]),
    dict(name="Vertex A11y", tagline="Real-time accessibility insights for developers", prize="Best Emerging - 1st",
         tech=["javascript", "chrome extensions", "node.js", "openai"],
         topics=["accessibility", "developer tools"], career=["product engineering", "software engineering"]),
    dict(name="Orion", tagline="The onboarding buddy for new teammates", prize="Best Emerging - 2nd",
         tech=["react", "flask", "python", "postgresql", "chromadb", "scikit-learn"],
         topics=["developer productivity", "rag", "onboarding"], career=["software engineering", "developer experience"]),
    dict(name="Dispatch", tagline="VR locomotion for accessible immersive training", prize="Hall of Illusions - 1st",
         tech=["unity", "c#", "c++", "steamvr", "platformio"],
         topics=["virtual reality", "accessibility", "hardware"], career=["xr engineering", "game development"]),
    dict(name="Hall of Us", tagline="Relive photos in an immersive Quest 3 museum", prize="Hall of Illusions - 2nd",
         tech=["unity", "meta quest", "next.js", "langchain", "openai", "postgresql"],
         topics=["virtual reality", "generative ai", "photography"], career=["xr engineering", "creative technology"]),
    dict(name="VisionNav", tagline="Helping the visually impaired navigate through sound", prize="The Curator's Cause - 1st",
         tech=["swift", "yolo", "opencv", "mediapipe", "gemini", "speech to text"],
         topics=["accessibility", "computer vision", "ios development"], career=["mobile engineering", "assistive tech"]),
    dict(name="Caladrius", tagline="Privacy-first AI triage assistant", prize="The Curator's Cause - 2nd",
         tech=["fastapi", "langgraph", "next.js", "mongodb", "aws", "typescript"],
         topics=["healthcare", "ai agents", "privacy"], career=["health tech", "ml engineering"]),
    dict(name="graphaura", tagline="AI-powered 3D knowledge graph of memories", prize="Crypt of Data - 1st",
         tech=["fastapi", "neo4j", "pgvector", "redis", "next.js", "react-force-graph"],
         topics=["knowledge graphs", "data visualization", "rag"], career=["data engineering", "ai research"]),
    dict(name="Tradegist", tagline="Advanced trading behavior analysis", prize="Crypt of Data - 2nd",
         tech=["python", "fastapi", "react", "langchain", "openai", "postgresql"],
         topics=["quantitative finance", "trading", "llm apps"], career=["quantitative research", "fintech"]),
    dict(name="BikeBuddy", tagline="Rear-view camera and turn signals for bikes", prize="The Gadget Gallery - 1st",
         tech=["esp32", "arduino", "c++", "react native", "expo", "3d printing"],
         topics=["embedded systems", "hardware", "mobility"], career=["hardware startups", "robotics"]),
    dict(name="Dotify", tagline="Bringing the world to your fingertips (braille display)", prize="The Gadget Gallery - 2nd",
         tech=["arduino", "c++", "cad", "gemini", "python"],
         topics=["accessibility", "hardware", "embedded systems"], career=["assistive tech", "hardware engineering"]),
    dict(name="The Kick is Good", tagline="Computer vision for true field goal distance", prize="PrizePicks - Signal from the Noise",
         tech=["opencv", "python", "react"],
         topics=["sports analytics", "computer vision"], career=["sports tech", "data science"]),
    dict(name="Sideline", tagline="Real-time sports second-screen challenges", prize="PrizePicks - Second Screen",
         tech=["react native", "expo", "firebase", "node.js", "websockets", "openai"],
         topics=["sports analytics", "mobile apps", "real-time systems"], career=["mobile engineering", "sports tech"]),
    dict(name="Vital", tagline="Agentic workflows linking clinical guidelines and policy", prize="Impiricus",
         tech=["react", "supabase", "typescript", "openai"],
         topics=["healthcare", "ai agents", "health policy"], career=["health tech", "product engineering"]),
    dict(name="Medicus", tagline="Connecting medtech companies with providers", prize="Impiricus",
         tech=["docker", "mastra", "perplexity", "postgresql", "react", "typescript"],
         topics=["healthcare", "marketplaces", "ai agents"], career=["health tech", "startups"]),
    dict(name="Doc McQuery", tagline="Smarter medical literature search", prize="Impiricus",
         tech=["flask", "pgvector", "sentence transformers", "react", "postgresql", "python"],
         topics=["healthcare", "semantic search", "rag"], career=["health tech", "ml engineering"]),
    dict(name="I'd Rather Scroll", tagline="Productive doomscrolling for finance", prize="Capital One - Best Financial Hack",
         tech=["react"],
         topics=["fintech", "financial literacy", "consumer apps"], career=["fintech", "product design"]),
    dict(name="HR Audit", tagline="AI agents for banking fraud detection", prize="Capital One - Best Financial Hack",
         tech=["mastra", "flask", "node.js", "twilio", "openai", "typescript"],
         topics=["fraud detection", "fintech", "ai agents"], career=["fintech", "security engineering"]),
    dict(name="Atlas", tagline="Unified memory across your AI stack", prize="Best Use of Mastra / CedarOS",
         tech=["electron", "three.js", "mastra", "vercel ai sdk", "typescript", "react"],
         topics=["ai agents", "developer productivity", "llm apps"], career=["ai engineering", "developer experience"]),
    dict(name="InfraBlocks", tagline="Making cloud services simple", prize="Warp - Best Developer Tool",
         tech=["next.js", "react", "tailwind css", "typescript", "openai"],
         topics=["cloud infrastructure", "devops", "developer tools"], career=["devops", "platform engineering"]),
    dict(name="CanDraw", tagline="AI copilot for whiteboards", prize="Ergo - Best Use of Mastra",
         tech=["mastra", "react", "node.js", "openai", "typescript"],
         topics=["generative ai", "creative tools", "edtech"], career=["product engineering", "ai engineering"]),
    dict(name="Ming Management Training", tagline="AI-native executive coaching", prize="MLH - Best Use of Gemini API",
         tech=["next.js", "gemini", "mastra", "cloudflare", "typescript"],
         topics=["edtech", "ai coaching", "llm apps"], career=["edtech", "product engineering"]),
    dict(name="Waste2Taste", tagline="Measuring dining-hall plate waste", prize="MLH - Best Use of Snowflake",
         tech=["python", "raspberry pi", "segment anything", "snowflake", "supabase"],
         topics=["sustainability", "computer vision", "iot"], career=["climate tech", "data engineering"]),
    dict(name="Grindstone", tagline="AI agent goal tracker that gamifies goals", prize="MLH - Best AI App with Cloudflare",
         tech=["swift", "swiftui", "cloudflare workers", "mastra", "gemini", "next.js"],
         topics=["ai agents", "ios development", "productivity"], career=["mobile engineering", "ai engineering"]),
    dict(name="CommitSense", tagline="Explain legacy code with RAG", prize="MLH - Best Domain Name (GoDaddy)",
         tech=["react", "snowflake cortex", "gemini", "typescript", "vite"],
         topics=["developer tools", "rag", "legacy code"], career=["software engineering", "developer experience"]),
]
